#! /bin/sh

### BEGIN INIT INFO
# Provides:		security-cam
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Security Camera Server
### END INIT INFO

BOT_USER="pi"
BOT_PATH="/home/pi/DataScience/apps/security-cam/security-cam.py"
DIR_PATH="${BOT_PATH%/*}"
CFG_PATH=""
EXPECTED_OUTPUT="security-cam"
DAEMON_NAME="Security Camera Server"

set -e

run_cmd() {
	if test -f ${CFG_PATH}; then
		su ${BOT_USER} -c "cd ${DIR_PATH} && ${BOT_PATH} --config ${CFG_PATH} $1"
	else
		su ${BOT_USER} -c "cd ${DIR_PATH} && ${BOT_PATH} $1"
	fi
}

PROC_CTRL=${0##*/}

# /etc/init.d/security-cam: start and stop the Security Camera daemon

test -d ${DIR_PATH} || ( >2& echo "Directory not found: ${DIR_PATH}" && exit 1 )
test -x ${BOT_PATH} || ( >2& echo "File not found: ${BOT_PATH}" && exit 1 )
( run_cmd 2>&1 | grep -q "${EXPECTED_OUTPUT}" ) 2>/dev/null || ( >2& echo "Unexpected output from command ${BOT_PATH}" && exit 1 )

umask 022

if test -f ${DIR_PATH}/environment; then
    . ${DIR_PATH}/environment
fi
. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting ${DAEMON_NAME} service" "${PROC_CTRL}" || true
    source ~/.venvs/python-security-cam/bin-activate
	if ( run_cmd $1 2>/dev/null ); then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
    deactivate || true
	;;
  stop)
	log_daemon_msg "Stopping ${DAEMON_NAME} service" "${PROC_CTRL}" || true
    source ~/.venvs/python-security-cam/bin-activate
	if ( run_cmd $1 2>/dev/null ); then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
    deactivate || true
	;;

  reload|force-reload)
	log_daemon_msg "Reloading ${DAEMON_NAME} service configuration" "${PROC_CTRL}" || true
    source ~/.venvs/python-security-cam/bin-activate
	if ( run_cmd $1 2>/dev/null ); then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
    deactivate || true
	;;

  restart)
	log_daemon_msg "Restarting ${DAEMON_NAME} service" "${PROC_CTRL}" || true
    source ~/.venvs/python-security-cam/bin-activate
	if ( run_cmd "stop" 2>/dev/null ); then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	if ( run_cmd "start" 2>/dev/null ); then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
    deactivate
	;;

  status)
	echo ${EXPECTED_OUTPUT}
    #source ~/.venvs/python-security-cam/bin-activate
	#( ${EXEC_BIN} status 2>/dev/null ) && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/${PROC_CTRL} {start|stop|reload|force-reload|restart|status}" || true
	exit 1
esac

exit 0
